let masterExerciseList = [
    ["Ab Crunch Machine", "Weight"],
    ["Ab Roller", "Weight"],
    ["Adductor", "Weight"],
    ["Adductor/Groin", "Weight"],
    ["Advanced Kettlebell Windmill", "Weight"],
    ["Air Bike", "Weight"],
    ["Alternate Hammer Curl", "Weight"],
    ["Alternate Heel Touchers", "Weight"],
    ["Alternate Incline Dumbbell Curl", "Weight"],
    ["Alternate Leg Diagonal Bound", "Weight"],
    ["Alternating Cable Shoulder Press", "Weight"],
    ["Alternating Deltoid Raise", "Weight"],
    ["Alternating Floor Press", "Weight"],
    ["Alternating Hang Clean", "Weight"],
    ["Alternating Kettlebell Press", "Weight"],
    ["Alternating Kettlebell Row", "Weight"],
    ["Alternating Renegade Row", "Weight"],
    ["Ankle Circles", "Weight"],
    ["Ankle On The Knee", "Weight"],
    ["Anterior Tibialis-Smr", "Weight"],
    ["Anti-Gravity Press", "Weight"],
    ["Arm Circles", "Weight"],
    ["Arnold Dumbbell Press", "Weight"],
    ["Around The Worlds", "Weight"],
    ["Atlas Stone Trainer", "Weight"],
    ["Atlas Stones", "Weight"],
    ["Axle Deadlift", "Weight"],
    ["Ab Crunch Machine", "Weight"],
    ["Ab Roller", "Weight"],
    ["Adductor", "Weight"],
    ["Adductor/Groin", "Weight"],
    ["Advanced Kettlebell Windmill", "Weight"],
    ["Air Bike", "Weight"],
    ["Alternate Hammer Curl", "Weight"],
    ["Alternate Heel Touchers", "Weight"],
    ["Alternate Incline Dumbbell Curl", "Weight"],
    ["Alternate Leg Diagonal Bound", "Weight"],
    ["Alternating Cable Shoulder Press", "Weight"],
    ["Alternating Deltoid Raise", "Weight"],
    ["Alternating Floor Press", "Weight"],
    ["Alternating Hang Clean", "Weight"],
    ["Alternating Kettlebell Press", "Weight"],
    ["Alternating Kettlebell Row", "Weight"],
    ["Alternating Renegade Row", "Weight"],
    ["Ankle Circles", "Weight"],
    ["Ankle On The Knee", "Weight"],
    ["Anterior Tibialis-Smr", "Weight"],
    ["Anti-Gravity Press", "Weight"],
    ["Arm Circles", "Weight"],
    ["Arnold Dumbbell Press", "Weight"],
    ["Around The Worlds", "Weight"],
    ["Atlas Stone Trainer", "Weight"],
    ["Atlas Stones", "Weight"],
    ["Axle Deadlift", "Weight"],
    ["Back Flyes", "Weight"],
    ["Backward Drag", "Weight"],
    ["Backward Medicine Ball Throw", "Weight"],
    ["Balance Board", "Weight"],
    ["Ball Leg Curl", "Weight"],
    ["Band Assisted Pull-Up", "Weight"],
    ["Band Good Morning", "Weight"],
    ["Band Good Morning (Pull Through)", "Weight"],
    ["Band Hip Adductions", "Weight"],
    ["Band Pull Apart", "Weight"],
    ["Band Skull Crusher", "Weight"],
    ["Barbell Ab Rollout", "Weight"],
    ["Barbell Ab Rollout", "Weight"],
    ["Barbell Bench Press", "Weight"],
    ["Barbell Curl", "Weight"],
    ["Barbell Curls Lying Against An Incline", "Weight"],
    ["Barbell Deadlift", "Weight"],
    ["Barbell Full Squat", "Weight"],
    ["Barbell Glute Bridge", "Weight"],
    ["Barbell Guillotine Bench Press", "Weight"],
    ["Barbell Hack Squat", "Weight"],
    ["Barbell Hip Thrust", "Weight"],
    ["Barbell Incline Bench Press ", "Weight"],
    ["Barbell Incline Shoulder Raise", "Weight"],
    ["Barbell Lunge", "Weight"],
    ["Barbell Rear Delt Row", "Weight"],
    ["Barbell Rollout From Bench", "Weight"],
    ["Barbell Seated Calf Raise", "Weight"],
    ["Barbell Shoulder Press", "Weight"],
    ["Barbell Shrug", "Weight"],
    ["Barbell Shrug Behind The Back", "Weight"],
    ["Barbell Side Bend", "Weight"],
    ["Barbell Side Split Squat", "Weight"],
    ["Barbell Squat", "Weight"],
    ["Barbell Squat To A Bench", "Weight"],
    ["Barbell Step Ups", "Weight"],
    ["Barbell Walking Lunge", "Weight"],
    ["Battling Ropes", "Weight"],
    ["Bear Crawl Sled Drags", "Weight"],
    ["Bench Dips", "Weight"],
    ["Bench Jump", "Weight"],
    ["Bench Press - With Bands", "Weight"],
    ["Bench Press With Chains", "Weight"],
    ["Bench Sprint", "Weight"],
    ["Bent Over Barbell Row", "Weight"],
    ["Bent Over Dumbbell Rear Delt Raise With Head On Bench", "Weight"],
    ["Bent Over Low-Pulley Side Lateral", "Weight"],
    ["Bent Over One-Arm Long Bar Row", "Weight"],
    ["Bent Over Two-Arm Long Bar Row", "Weight"],
    ["Bent Over Two-Dumbbell Row", "Weight"],
    ["Bent Press", "Weight"],
    ["Bent-Arm Barbell Pullover", "Weight"],
    ["Bent-Arm Dumbbell Pullover", "Weight"],
    ["Bent-Knee Hip Raise", "Weight"],
    ["Bicycling", "Weight"],
    ["Bicycling", "Weight"],
    ["Board Press", "Weight"],
    ["Body Tricep Press", "Weight"],
    ["Body-Up", "Weight"],
    ["Bodyweight Flyes", "Weight"],
    ["Bodyweight Mid Row", "Weight"],
    ["Bodyweight Squat", "Weight"],
    ["Bodyweight Walking Lunge", "Weight"],
    ["Bosu Ball Cable Crunch With Side Bends", "Weight"],
    ["Bottoms Up", "Weight"],
    ["Bottoms-Up Clean From The Hang Position", "Weight"],
    ["Box Jump (Multiple Response)", "Weight"],
    ["Box Skip", "Weight"],
    ["Box Squat", "Weight"],
    ["Box Squat With Bands", "Weight"],
    ["Box Squat With Chains", "Weight"],
    ["Brachialis-Smr", "Weight"],
    ["Bradford/Rocky Presses", "Weight"],
    ["Butt Lift (Bridge)", "Weight"],
    ["Butt-Ups", "Weight"],
    ["Butterfly", "Weight"],
    ["Cable Chest Press", "Weight"],
    ["Cable Crossover", "Weight"],
    ["Cable Crunch", "Weight"],
    ["Cable Deadlifts", "Weight"],
    ["Cable Hammer Curls", "Weight"],
    ["Cable Hip Adduction", "Weight"],
    ["Cable Incline Pushdown", "Weight"],
    ["Cable Incline Triceps Extension", "Weight"],
    ["Cable Internal Rotation", "Weight"],
    ["Cable Iron Cross", "Weight"],
    ["Cable Judo Flip", "Weight"],
    ["Cable Lying Triceps Extension", "Weight"],
    ["Cable One Arm Tricep Extension", "Weight"],
    ["Cable Preacher Curl", "Weight"],
    ["Cable Rear Delt Fly", "Weight"],
    ["Cable Reverse Crunch", "Weight"],
    ["Cable Rope Overhead Triceps Extension", "Weight"],
    ["Cable Rope Rear-Delt Rows", "Weight"],
    ["Cable Russian Twists", "Weight"],
    ["Cable Seated Crunch", "Weight"],
    ["Cable Seated Lateral Raise", "Weight"],
    ["Cable Shoulder Press", "Weight"],
    ["Cable Shrugs", "Weight"],
    ["Cable Tuck Reverse Crunch", "Weight"],
    ["Cable Wrist Curl", "Weight"],
    ["Calf Press", "Weight"],
    ["Calf Press On The Leg Press Machine", "Weight"],
    ["Calf Raises", "Weight"],
    ["Calf-Machine Shoulder Shrug", "Weight"],
    ["Calves-Smr", "Weight"],
    ["Car Deadlift", "Weight"],
    ["Car Drivers", "Weight"],
    ["Carioca Quick Step", "Weight"],
    ["Catch And Overhead Throw", "Weight"],
    ["Chain Handle Extension", "Weight"],
    ["Chain Press", "Weight"],
    ["Chair Squat", "Weight"],
    ["Chin-Up", "Weight"],
    ["Circus Bell", "Weight"],
    ["Clean", "Weight"],
    ["Clean And Jerk", "Weight"],
    ["Clean And Press", "Weight"],
    ["Clean Deadlift", "Weight"],
    ["Clean From Blocks", "Weight"],
    ["Clean Pull", "Weight"],
    ["Clean Shrug", "Weight"],
    ["Clock Push-Up", "Weight"],
    ["Close-Grip Barbell Bench Press", "Weight"],
    ["Close-Grip Dumbbell Press", "Weight"],
    ["Close-Grip Ez Bar Curl", "Weight"],
    ["Close-Grip Ez-Bar Curl With Band", "Weight"],
    ["Close-Grip Ez-Bar Press", "Weight"],
    ["Close-Grip Front Lat Pulldown", "Weight"],
    ["Close-Grip Push-Up Off Of A Dumbbell", "Weight"],
    ["Close-Grip Standing Barbell Curl", "Weight"],
    ["Close Neutral Grip Low Cable Row", "Weight"],
    ["Cocoons", "Weight"],
    ["Conan'S Wheel", "Weight"],
    ["Concentration Curls", "Weight"],
    ["Cross Body Hammer Curl", "Weight"],
    ["Cross Over", "Weight"],
    ["Cross-Body Crunch", "Weight"],
    ["Crossover Reverse Lunge", "Weight"],
    ["Crucifix", "Weight"],
    ["Crunches", "Weight"],
    ["Cuban Press", "Weight"],
    ["Deadlift With Bands", "Weight"],
    ["Deadlift With Chains", "Weight"],
    ["Decline Barbell Bench Press", "Weight"],
    ["Decline Close-Grip Bench To Skull Crusher", "Weight"],
    ["Decline Crunch", "Weight"],
    ["Decline Dumbbell Bench Press", "Weight"],
    ["Decline Dumbbell Flyes", "Weight"],
    ["Decline Dumbbell Triceps Extension", "Weight"],
    ["Decline Ez Bar Triceps Extension", "Weight"],
    ["Decline Oblique Crunch", "Weight"],
    ["Decline Push-Up", "Weight"],
    ["Decline Reverse Crunch", "Weight"],
    ["Decline Smith Press", "Weight"],
    ["Deficit Deadlift", "Weight"],
    ["Depth Jump Leap", "Weight"],
    ["Dip Machine", "Weight"],
    ["Dips - Chest Version", "Weight"],
    ["Dips - Triceps Version", "Weight"],
    ["Donkey Calf Raises", "Weight"],
    ["Double Kettlebell Alternating Hang Clean", "Weight"],
    ["Double Kettlebell Jerk", "Weight"],
    ["Double Kettlebell Push Press", "Weight"],
    ["Double Kettlebell Snatch", "Weight"],
    ["Double Kettlebell Windmill", "Weight"],
    ["Double Leg Butt Kick", "Weight"],
    ["Downward Facing Balance", "Weight"],
    ["Drag Curl", "Weight"],
    ["Drop Push", "Weight"],
    ["Dumbbell Alternate Bicep Curl", "Weight"],
    ["Dumbbell Bench Press", "Weight"],
    ["Dumbbell Bicep Curl", "Weight"],
    ["Dumbbell Clean", "Weight"],
    ["Dumbbell Floor Press", "Weight"],
    ["Dumbbell Flyes", "Weight"],
    ["Dumbbell Incline Row", "Weight"],
    ["Dumbbell Incline Shoulder Raise", "Weight"],
    ["Dumbbell Lunges", "Weight"],
    ["Dumbbell Lying One-Arm Rear Lateral Raise", "Weight"],
    ["Dumbbell Lying Pronation", "Weight"],
    ["Dumbbell Lying Rear Lateral Raise", "Weight"],
    ["Dumbbell Lying Supination", "Weight"],
    ["Dumbbell One-Arm Shoulder Press", "Weight"],
    ["Dumbbell One-Arm Triceps Extension", "Weight"],
    ["Dumbbell One-Arm Upright Row", "Weight"],
    ["Dumbbell Prone Incline Curl", "Weight"],
    ["Dumbbell Raise", "Weight"],
    ["Dumbbell Rear Lunge", "Weight"],
    ["Dumbbell Scaption", "Weight"],
    ["Dumbbell Seated Box Jump", "Weight"],
    ["Dumbbell Seated One-Leg Calf Raise", "Weight"],
    ["Dumbbell Shoulder Press", "Weight"],
    ["Dumbbell Shrug", "Weight"],
    ["Dumbbell Side Bend", "Weight"],
    ["Dumbbell Squat", "Weight"],
    ["Dumbbell Squat To A Bench", "Weight"],
    ["Dumbbell Step Ups", "Weight"],
    ["Dumbbell Tricep Extension", "Weight"],
    ["Elbow Circles", "Weight"],
    ["Elbow To Knee", "Weight"],
    ["Elbows Back", "Weight"],
    ["Elevated Back Lunge", "Weight"],
    ["Elevated Cable Rows", "Weight"],
    ["Elliptical Trainer", "Weight"],
    ["Exercise Ball Crunch", "Weight"],
    ["Exercise Ball Pull-In", "Weight"],
    ["Extended Range One-Arm Kettlebell Floor Press", "Weight"],
    ["External Rotation", "Weight"],
    ["External Rotation With Band", "Weight"],
    ["External Rotation With Cable", "Weight"],
    ["Ez-Bar Curl", "Weight"],
    ["Ez-Bar Skullcrusher", "Weight"],
    ["Face Pull", "Weight"],
    ["Farmer's Walk", "Weight"],
    ["Fast Skipping", "Weight"],
    ["Finger Curls", "Weight"],
    ["Flat Bench Cable Flyes", "Weight"],
    ["Flat Bench Leg Pull-In", "Weight"],
    ["Flat Bench Lying Leg Raise", "Weight"],
    ["Flexor Incline Dumbbell Curls", "Weight"],
    ["Floor Glute-Ham Raise", "Weight"],
    ["Floor Press", "Weight"],
    ["Floor Press With Chains", "Weight"],
    ["Flutter Kicks", "Weight"],
    ["Foot-Smr", "Weight"],
    ["Forward Drag With Press", "Weight"],
    ["Frankenstein Squat", "Weight"],
    ["Freehand Jump Squat", "Weight"],
    ["Frog Hops", "Weight"],
    ["Frog Sit-Ups", "Weight"],
    ["Front Barbell Squat", "Weight"],
    ["Front Barbell Squat To A Bench", "Weight"],
    ["Front Box Jump", "Weight"],
    ["Front Cable Raise", "Weight"],
    ["Front Cone Hops", "Weight"],
    ["Front Dumbbell Raise", "Weight"],
    ["Front Incline Dumbbell Raise", "Weight"],
    ["Front Leg Raises", "Weight"],
    ["Front Plate Raise", "Weight"],
    ["Front Raise And Pullover", "Weight"],
    ["Front Squat (Clean Grip)", "Weight"],
    ["Front Squats With Two Kettlebells", "Weight"],
    ["Front Two-Dumbbell Raise", "Weight"],
    ["Full Range-Of-Motion Lat Pulldown", "Weight"],
    ["Gironda Sternum Chins", "Weight"],
    ["Glute Ham Raise", "Weight"],
    ["Glute Kickback", "Weight"],
    ["Goblet Squat", "Weight"],
    ["Good Morning", "Weight"],
    ["Good Morning Off Pins", "Weight"],
    ["Gorilla Chin/Crunch", "Weight"],
    ["Groiners", "Weight"],
    ["Hack Squat", "Weight"],
    ["Hammer Curls", "Weight"],
    ["Hammer Grip Incline Db Bench Press", "Weight"],
    ["Hamstring-Smr", "Weight"],
    ["Handstand Push-Ups", "Weight"],
    ["Hang Clean", "Weight"],
    ["Hang Snatch", "Weight"],
    ["Hanging Bar Good Morning", "Weight"],
    ["Hanging Leg Raise", "Weight"],
    ["Hanging Pike", "Weight"],
    ["Heaving Snatch Balance", "Weight"],
    ["Heavy Bag Thrust", "Weight"],
    ["High Cable Curls", "Weight"],
    ["Hip Circles (Prone)", "Weight"],
    ["Hip Crossover,", "Weight"],
    ["Hip Extension With Bands", "Weight"],
    ["Hip Flexion With Band", "Weight"],
    ["Hip Lift With Band", "Weight"],
    ["Hug A Ball", "Weight"],
    ["Hug Knees To Chest", "Weight"],
    ["Hurdle Hops", "Weight"],
    ["Hyperextensions (Back Extensions)", "Weight"],
    ["Iliotibial Tract-Smr", "Weight"],
    ["Incline Barbell Triceps Extension", "Weight"],
    ["Incline Bench Pull", "Weight"],
    ["Incline Cable Chest Press", "Weight"],
    ["Incline Cable Flye", "Weight"],
    ["Incline Dumbbell Curl", "Weight"],
    ["Incline Dumbbell Flyes", "Weight"],
    ["Incline Dumbbell Press", "Weight"],
    ["Incline Hammer Curls", "Weight"],
    ["Incline Inner Biceps Curl", "Weight"],
    ["Incline Push-Up", "Weight"],
    ["Internal Rotation With Band", "Weight"],
    ["Inverted Row", "Weight"],
    ["Inverted Row With Straps", "Weight"],
    ["Iron Cross", "Weight"],
    ["Isometric Chest Squeezes", "Weight"],
    ["Isometric Neck Exercise - Front And Back", "Weight"],
    ["Isometric Neck Exercise - Sides", "Weight"],
    ["Isometric Wipers", "Weight"],
    ["Jackknife Sit-Up", "Weight"],
    ["Janda Sit-Up", "Weight"],
    ["Jefferson Squats", "Weight"],
    ["Jerk Balance", "Weight"],
    ["Jerk Dip Squat", "Weight"],
    ["Jm Press", "Weight"],
    ["Jogging-Treadmill", "Weight"],
    ["Keg Load", "Weight"],
    ["Kettlebell Arnold Press", "Weight"],
    ["Kettlebell Dead Clean", "Weight"],
    ["Kettlebell Figure 8", "Weight"],
    ["Kettlebell Hang Clean", "Weight"],
    ["Kettlebell One-Legged Deadlift", "Weight"],
    ["Kettlebell Pass Between The Legs", "Weight"],
    ["Kettlebell Pirate Ships", "Weight"],
    ["Kettlebell Pistol Squat", "Weight"],
    ["Kettlebell Seated Press", "Weight"],
    ["Kettlebell Seesaw Press", "Weight"],
    ["Kettlebell Sumo High Pull", "Weight"],
    ["Kettlebell Thruster", "Weight"],
    ["Kettlebell Turkish Get-Up", "Weight"],
    ["Kettlebell Windmill", "Weight"],
    ["Kipping Muscle Up", "Weight"],
    ["Knee Across The Body", "Weight"],
    ["Knee Circles", "Weight"],
    ["Knee Tuck Jump", "Weight"],
    ["Knee/Hip Raise On Parallel Bars", "Weight"],
    ["Kneeling Arm Drill", "Weight"],
    ["Kneeling Cable Crunch With Alternating Oblique Twists", "Weight"],
    ["Kneeling Cable Triceps Extension", "Weight"],
    ["Kneeling High Pulley Row", "Weight"],
    ["Kneeling Hip Flexor", "Weight"],
    ["Kneeling Jump Squat", "Weight"],
    ["Kneeling Single-Arm High Pulley Row", "Weight"],
    ["Kneeling Squat", "Weight"],
    ["Landmine 180'S", "Weight"],
    ["Landmine Linear Jammer", "Weight"],
    ["Lateral Bound", "Weight"],
    ["Lateral Box Jump", "Weight"],
    ["Lateral Cone Hops", "Weight"],
    ["Lateral Raise", "Weight"],
    ["Latissimus Dorsi-Smr", "Weight"],
    ["Leg Extensions", "Weight"],
    ["Leg Lift", "Weight"],
    ["Leg Press", "Weight"],
    ["Leg Pull-In", "Weight"],
    ["Leg-Over Floor Press", "Weight"],
    ["Leverage Chest Press", "Weight"],
    ["Leverage Deadlift", "Weight"],
    ["Leverage Decline Chest Press", "Weight"],
    ["Leverage High Row", "Weight"],
    ["Leverage Incline Chest Press", "Weight"],
    ["Leverage Iso Row", "Weight"],
    ["Leverage Shoulder Press", "Weight"],
    ["Leverage Shrug", "Weight"],
    ["Linear 3-Part Start Technique", "Weight"],
    ["Linear Acceleration Wall Drill", "Weight"],
    ["Linear Depth Jump", "Weight"],
    ["Log Lift", "Weight"],
    ["London Bridges", "Weight"],
    ["Looking At Ceiling", "Weight"],
    ["Low Cable Crossover", "Weight"],
    ["Low Cable Triceps Extension", "Weight"],
    ["Low Pulley Row To Neck", "Weight"],
    ["Lower Back Curl", "Weight"],
    ["Lower Back-Smr", "Weight"],
    ["Lunge Pass Through", "Weight"],
    ["Lunge Sprint", "Weight"],
    ["Lying Bent Leg Groin", "Weight"],
    ["Lying Cable Curl", "Weight"],
    ["Lying Cambered Barbell Row", "Weight"],
    ["Lying Close-Grip Bar Curl", "Weight"],
    ["Lying Close-Grip Barbell Triceps Extension", "Weight"],
    ["Lying Crossover", "Weight"],
    ["Lying Dumbbell Tricep Extension", "Weight"],
    ["Lying Face Down Plate Neck Resistance", "Weight"],
    ["Lying Face Up Plate Neck Resistance", "Weight"],
    ["Lying Glute", "Weight"],
    ["Lying Hamstring", "Weight"],
    ["Lying High Bench Barbell Curl", "Weight"],
    ["Lying Leg Curls", "Weight"],
    ["Lying Machine Squat", "Weight"],
    ["Lying One-Arm Lateral Raise", "Weight"],
    ["Lying Prone Quadriceps", "Weight"],
    ["Lying Rear Delt Raise", "Weight"],
    ["Lying Supine Dumbbell Curl", "Weight"],
    ["Lying T-Bar Row", "Weight"],
    ["Lying Triceps Press", "Weight"],
    ["Machine Bench Press", "Weight"],
    ["Machine Bicep Curl", "Weight"],
    ["Machine Pec Fly", "Weight"],
    ["Machine Preacher Curls", "Weight"],
    ["Machine Shoulder (Military) Press", "Weight"],
    ["Machine Triceps Extension", "Weight"],
    ["Medicine Ball Chest Pass", "Weight"],
    ["Medicine Ball Full Twist", "Weight"],
    ["Medicine Ball Scoop Throw", "Weight"],
    ["Middle Back Shrug", "Weight"],
    ["Mixed Grip Chin", "Weight"],
    ["Monster Walk", "Weight"],
    ["Mountain Climbers", "Weight"],
    ["Moving Claw Series", "Weight"],
    ["Muscle Snatch", "Weight"],
    ["Muscle Up", "Weight"],
    ["Narrow Stance Hack Squats", "Weight"],
    ["Narrow Stance Leg Press", "Weight"],
    ["Narrow Stance Squats", "Weight"],
    ["Natural Glute Ham Raise", "Weight"],
    ["Neck Press", "Weight"],
    ["Neck-Smr", "Weight"],
    ["Oblique Crunches", "Weight"],
    ["Olympic Squat", "Weight"],
    ["One Arm Against Wall", "Weight"],
    ["One Arm Chin-Up", "Weight"],
    ["One Arm Dumbbell Bench Press", "Weight"],
    ["One Arm Dumbbell Preacher Curl", "Weight"],
    ["One Arm Floor Press", "Weight"],
    ["One Arm Lat Pulldown", "Weight"],
    ["One Arm Pronated Dumbbell Triceps Extension", "Weight"],
    ["One Arm Supinated Dumbbell Triceps Extension", "Weight"],
    ["One Half Locust", "Weight"],
    ["One Handed Hang", "Weight"],
    ["One Knee To Chest", "Weight"],
    ["One Leg Barbell Squat", "Weight"],
    ["One-Arm Dumbbell Row", "Weight"],
    ["One-Arm Flat Bench Dumbbell Flye", "Weight"],
    ["One-Arm High-Pulley Cable Side Bends", "Weight"],
    ["One-Arm Incline Lateral Raise", "Weight"],
    ["One-Arm Kettlebell Clean", "Weight"],
    ["One-Arm Kettlebell Clean And Jerk", "Weight"],
    ["One-Arm Kettlebell Floor Press", "Weight"],
    ["One-Arm Kettlebell Jerk", "Weight"],
    ["One-Arm Kettlebell Military Press To The Side", "Weight"],
    ["One-Arm Kettlebell Para Press", "Weight"],
    ["One-Arm Kettlebell Push Press", "Weight"],
    ["One-Arm Kettlebell Row", "Weight"],
    ["One-Arm Kettlebell Snatch", "Weight"],
    ["One-Arm Kettlebell Split Jerk", "Weight"],
    ["One-Arm Kettlebell Split Snatch", "Weight"],
    ["One-Arm Kettlebell Swings", "Weight"],
    ["One-Arm Long Bar Row", "Weight"],
    ["One-Arm Medicine Ball Slam", "Weight"],
    ["One-Arm Open Palm Kettlebell Clean", "Weight"],
    ["One-Arm Overhead Kettlebell Squats", "Weight"],
    ["One-Arm Side Deadlift", "Weight"],
    ["One-Arm Side Laterals", "Weight"],
    ["One-Legged Cable Kickback", "Weight"],
    ["Open Palm Kettlebell Clean", "Weight"],
    ["Otis-Up", "Weight"],
    ["Overhead Cable Curl", "Weight"],
    ["Overhead Lat", "Weight"],
    ["Overhead Slam", "Weight"],
    ["Overhead Squat", "Weight"],
    ["Overhead Triceps", "Weight"],
    ["Pallof Press With Rotation", "Weight"],
    ["Palms-Down Dumbbell Wrist Curl Over A Bench", "Weight"],
    ["Palms-Down Wrist Curl Over A Bench", "Weight"],
    ["Palms-Up Barbell Wrist Curl Over A Bench", "Weight"],
    ["Palms-Up Dumbbell Wrist Curl Over A Bench", "Weight"],
    ["Parallel Bar Dip", "Weight"],
    ["Pelvic Tilt Into Bridge", "Weight"],
    ["Peroneals-Smr", "Weight"],
    ["Physioball Hip Bridge", "Weight"],
    ["Pin Presses", "Weight"],
    ["Piriformis-Smr", "Weight"],
    ["Plank", "Weight"],
    ["Plank With Twist", "Weight"],
    ["Plate Pinch", "Weight"],
    ["Plate Twist", "Weight"],
    ["Platform Hamstring Slides", "Weight"],
    ["Plie Dumbbell Squat", "Weight"],
    ["Plyo Kettlebell Pushups", "Weight"],
    ["Plyo Push-Up", "Weight"],
    ["Power Clean", "Weight"],
    ["Power Clean From Blocks", "Weight"],
    ["Power Jerk", "Weight"],
    ["Power Partials", "Weight"],
    ["Power Snatch", "Weight"],
    ["Power Snatch From Blocks", "Weight"],
    ["Power Stairs", "Weight"],
    ["Preacher Curl", "Weight"],
    ["Preacher Hammer Dumbbell Curl", "Weight"],
    ["Press Sit-Up", "Weight"],
    ["Prone Manual Hamstring", "Weight"],
    ["Prowler Sprint", "Weight"],
    ["Pull Through", "Weight"],
    ["Pullups", "Weight"],
    ["Push Press", "Weight"],
    ["Push Up To Side Plank", "Weight"],
    ["Push-Up Wide", "Weight"],
    ["Pushups", "Weight"],
    ["Pyramid", "Weight"],
    ["Quadriceps-Smr", "Weight"],
    ["Quick Leap", "Weight"],
    ["Rack Delivery", "Weight"],
    ["Rack Pull With Bands", "Weight"],
    ["Rack Pulls", "Weight"],
    ["Rear Leg Raises", "Weight"],
    ["Recumbent Bike", "Weight"],
    ["Return Push From Stance", "Weight"],
    ["Reverse Band Bench Press", "Weight"],
    ["Reverse Band Box Squat", "Weight"],
    ["Reverse Band Deadlift", "Weight"],
    ["Reverse Band Power Squat", "Weight"],
    ["Reverse Band Sumo Deadlift", "Weight"],
    ["Reverse Barbell Curl", "Weight"],
    ["Reverse Barbell Preacher Curls", "Weight"],
    ["Reverse Cable Curl", "Weight"],
    ["Reverse Crunch", "Weight"],
    ["Reverse Flyes", "Weight"],
    ["Reverse Flyes With External Rotation", "Weight"],
    ["Reverse Grip Bent-Over Rows", "Weight"],
    ["Reverse Grip Cable Lat Pulldowns", "Weight"],
    ["Reverse Grip Cable Straight Bar Rows", "Weight"],
    ["Reverse Grip Triceps Pushdown", "Weight"],
    ["Reverse Hyperextension", "Weight"],
    ["Reverse Machine Flyes", "Weight"],
    ["Reverse Plate Curls", "Weight"],
    ["Reverse Triceps Bench Press", "Weight"],
    ["Rhomboids-Smr", "Weight"],
    ["Rickshaw Carry", "Weight"],
    ["Rickshaw Deadlift", "Weight"],
    ["Ring Dips", "Weight"],
    ["Rocket Jump", "Weight"],
    ["Rocking Standing Calf Raise", "Weight"],
    ["Rocky Pull-Ups/Pulldowns", "Weight"],
    ["Romanian Deadlift", "Weight"],
    ["Romanian Deadlift From Deficit", "Weight"],
    ["Rope Climb", "Weight"],
    ["Rope Crunch", "Weight"],
    ["Rope Jumping", "Weight"],
    ["Rope Straight-Arm Pulldown", "Weight"],
    ["Russian Twist", "Weight"],
    ["Sandbag Load", "Weight"],
    ["Scapular Pull-Up", "Weight"],
    ["Scissor Kick", "Weight"],
    ["Scissors Jump", "Weight"],
    ["Seated Band Hamstring Curl", "Weight"],
    ["Seated Barbell Military Press", "Weight"],
    ["Seated Barbell Twist", "Weight"],
    ["Seated Bent-Over One-Arm Dumbbell Triceps Extension", "Weight"],
    ["Seated Bent-Over Rear Delt Raise", "Weight"],
    ["Seated Bent-Over Two-Arm Dumbbell Triceps Extension", "Weight"],
    ["Seated Biceps", "Weight"],
    ["Seated Cable Rows", "Weight"],
    ["Seated Cable Shoulder Press", "Weight"],
    ["Seated Calf Raise", "Weight"],
    ["Seated Close-Grip Concentration Barbell Curl", "Weight"],
    ["Seated Dumbbell Curl", "Weight"],
    ["Seated Dumbbell Press", "Weight"],
    ["Seated Flat Bench Leg Pull-In", "Weight"],
    ["Seated Front Deltoid", "Weight"],
    ["Seated Glute", "Weight"],
    ["Seated Good Mornings", "Weight"],
    ["Seated Hamstring", "Weight"],
    ["Seated Head Harness Neck Resistance", "Weight"],
    ["Seated Leg Curl", "Weight"],
    ["Seated Leg Tucks", "Weight"],
    ["Seated One-Arm Cable Pulley Rows", "Weight"],
    ["Seated One-Arm Dumbbell Palms-Down Wrist Curl", "Weight"],
    ["Seated One-Arm Dumbbell Palms-Up Wrist Curl", "Weight"],
    ["Seated Palm-Up Barbell Wrist Curl", "Weight"],
    ["Seated Palms-Down Barbell Wrist Curl", "Weight"],
    ["Seated Side Lateral Raise", "Weight"],
    ["Seated Triceps Press", "Weight"],
    ["Seated Two-Arm Palms-Up Low-Pulley Wrist Curl", "Weight"],
    ["Seated V-Bar Row", "Weight"],
    ["See-Saw Press", "Weight"],
    ["Shotgun Row", "Weight"],
    ["Shoulder Circles", "Weight"],
    ["Shoulder Press", "Weight"],
    ["Shoulder Raise", "Weight"],
    ["Side Bridge", "Weight"],
    ["Side Hop-Sprint", "Weight"],
    ["Side Jackknife", "Weight"],
    ["Side Lateral Raise", "Weight"],
    ["Side Laterals To Front Raise", "Weight"],
    ["Side Leg Raises", "Weight"],
    ["Side Standing Long Jump", "Weight"],
    ["Side To Side Box Shuffle", "Weight"],
    ["Side To Side Chins", "Weight"],
    ["Side Wrist Pull", "Weight"],
    ["Single Dumbbell Raise", "Weight"],
    ["Single Leg Butt Kick", "Weight"],
    ["Single Leg Glute Bridge", "Weight"],
    ["Single Leg Push-Off", "Weight"],
    ["Single-Arm Cable Crossover", "Weight"],
    ["Single-Arm Linear Jammer", "Weight"],
    ["Single-Arm Push-Up", "Weight"],
    ["Single-Cone Sprint Drill", "Weight"],
    ["Single-Leg High Box Squat", "Weight"],
    ["Single-Leg Hop Progression", "Weight"],
    ["Single-Leg Lateral Hop", "Weight"],
    ["Single-Leg Leg Extension", "Weight"],
    ["Single-Leg Stride Jump", "Weight"],
    ["Sit Squats", "Weight"],
    ["Sit-Up", "Weight"],
    ["Sled Drag - Harness", "Weight"],
    ["Sled Overhead Backward Walk", "Weight"],
    ["Sled Overhead Triceps Extension", "Weight"],
    ["Sled Push", "Weight"],
    ["Sled Reverse Flye", "Weight"],
    ["Sled Row", "Weight"],
    ["Sledgehammer Swings", "Weight"],
    ["Smith Incline Shoulder Raise", "Weight"],
    ["Smith Machine Behind The Back Shrug", "Weight"],
    ["Smith Machine Bench Press", "Weight"],
    ["Smith Machine Bent Over Row", "Weight"],
    ["Smith Machine Calf Raise", "Weight"],
    ["Smith Machine Close-Grip Bench Press", "Weight"],
    ["Smith Machine Decline Press", "Weight"],
    ["Smith Machine Hang Power Clean", "Weight"],
    ["Smith Machine Hip Raise", "Weight"],
    ["Smith Machine Incline Bench Press", "Weight"],
    ["Smith Machine Leg Press", "Weight"],
    ["Smith Machine One-Arm Upright Row", "Weight"],
    ["Smith Machine Overhead Shoulder Press", "Weight"],
    ["Smith Machine Pistol Squat", "Weight"],
    ["Smith Machine Reverse Calf Raises", "Weight"],
    ["Smith Machine Shrug", "Weight"],
    ["Smith Machine Squat", "Weight"],
    ["Smith Machine Stiff-Legged Deadlift", "Weight"],
    ["Smith Machine Upright Row", "Weight"],
    ["Smith Single-Leg Split Squat", "Weight"],
    ["Snatch", "Weight"],
    ["Snatch Balance", "Weight"],
    ["Snatch Deadlift", "Weight"],
    ["Snatch From Blocks", "Weight"],
    ["Snatch Pull", "Weight"],
    ["Snatch Shrug", "Weight"],
    ["Speed Band Overhead Triceps", "Weight"],
    ["Speed Band Pushdown", "Weight"],
    ["Speed Box Squat", "Weight"],
    ["Speed Squats", "Weight"],
    ["Spell Caster", "Weight"],
    ["Spider Crawl", "Weight"],
    ["Spider Curl", "Weight"],
    ["Split Clean", "Weight"],
    ["Split Jerk", "Weight"],
    ["Split Jump", "Weight"],
    ["Split Snatch", "Weight"],
    ["Split Squat With Dumbbells", "Weight"],
    ["Split Squats", "Weight"],
    ["Squat Jerk", "Weight"],
    ["Squat With Bands", "Weight"],
    ["Squat With Chains", "Weight"],
    ["Squat With Plate Movers", "Weight"],
    ["Stairmaster", "Weight"],
    ["Standing Alternating Dumbbell Press", "Weight"],
    ["Standing Barbell Calf Raise", "Weight"],
    ["Standing Barbell Press Behind Neck", "Weight"],
    ["Standing Bent-Over One-Arm Dumbbell Triceps Extension", "Weight"],
    ["Standing Bent-Over Two-Arm Dumbbell Triceps Extension", "Weight"],
    ["Standing Biceps Cable Curl", "Weight"],
    ["Standing Bradford Press", "Weight"],
    ["Standing Cable Chest Press", "Weight"],
    ["Standing Cable Lift", "Weight"],
    ["Standing Cable Wood Chop", "Weight"],
    ["Standing Calf Raises", "Weight"],
    ["Standing Concentration Curl", "Weight"],
    ["Standing Dumbbell Calf Raise", "Weight"],
    ["Standing Dumbbell Press", "Weight"],
    ["Standing Dumbbell Reverse Curl", "Weight"],
    ["Standing Dumbbell Straight-Arm Front Delt Raise Above Head", "Weight"],
    ["Standing Dumbbell Triceps Extension", "Weight"],
    ["Standing Dumbbell Upright Row", "Weight"],
    ["Standing Front Barbell Raise Over Head", "Weight"],
    ["Standing Hip Circles", "Weight"],
    ["Standing Hip Flexors", "Weight"],
    ["Standing Inner-Biceps Curl", "Weight"],
    ["Standing Leg Curl", "Weight"],
    ["Standing Long Jump", "Weight"],
    ["Standing Low-Pulley Deltoid Raise", "Weight"],
    ["Standing Low-Pulley One-Arm Triceps Extension", "Weight"],
    ["Standing Military Press", "Weight"],
    ["Standing Olympic Plate Hand Squeeze", "Weight"],
    ["Standing One-Arm Cable Curl", "Weight"],
    ["Standing One-Arm Dumbbell Curl Over Incline Bench", "Weight"],
    ["Standing One-Arm Dumbbell Triceps Extension", "Weight"],
    ["Standing Overhead Barbell Triceps Extension", "Weight"],
    ["Standing Palm-In One-Arm Dumbbell Press", "Weight"],
    ["Standing Palms-In Dumbbell Press", "Weight"],
    ["Standing Palms-Up Barbell Behind The Back Wrist Curl", "Weight"],
    ["Standing Pelvic Tilt", "Weight"],
    ["Standing Rope Crunch", "Weight"],
    ["Standing Toe Touches", "Weight"],
    ["Standing Towel Triceps Extension", "Weight"],
    ["Standing Two-Arm Overhead Throw", "Weight"],
    ["Star Jump", "Weight"],
    ["Step Mill", "Weight"],
    ["Step-Up With Knee Raise", "Weight"],
    ["Stiff Leg Barbell Good Morning", "Weight"],
    ["Stiff-Legged Barbell Deadlift", "Weight"],
    ["Stiff-Legged Dumbbell Deadlift", "Weight"],
    ["Stomach Vacuum", "Weight"],
    ["Straight Bar Bench Mid Rows", "Weight"],
    ["Straight Raises On Incline Bench", "Weight"],
    ["Straight-Arm Dumbbell Pullover", "Weight"],
    ["Straight-Arm Pulldown", "Weight"],
    ["Stride Jump Crossover", "Weight"],
    ["Sumo Deadlift", "Weight"],
    ["Sumo Deadlift With Bands", "Weight"],
    ["Sumo Deadlift With Chains", "Weight"],
    ["Superman", "Weight"],
    ["Supine Chest Throw", "Weight"],
    ["Supine One-Arm Overhead Throw", "Weight"],
    ["Supine Two-Arm Overhead Throw", "Weight"],
    ["Suspended Push-Up", "Weight"],
    ["Suspended Reverse Crunch", "Weight"],
    ["Suspended Row", "Weight"],
    ["Suspended Split Squat", "Weight"],
    ["T-Bar Row With Handle", "Weight"],
    ["Tate Press", "Weight"],
    ["The Straddle", "Weight"],
    ["Thigh Abductor", "Weight"],
    ["Thigh Adductor", "Weight"],
    ["Tire Flip", "Weight"],
    ["Toe Touchers", "Weight"],
    ["Torso Rotation", "Weight"],
    ["Trail Running/Walking", "Weight"],
    ["Trap Bar Deadlift", "Weight"],
    ["Tricep Dumbbell Kickback", "Weight"],
    ["Triceps Overhead Extension With Rope", "Weight"],
    ["Triceps Pushdown - Rope", "Weight"],
    ["Triceps Pushdown - Straight Bar", "Weight"],
    ["Tuck Crunch", "Weight"],
    ["Two-Arm Dumbbell Preacher Curl", "Weight"],
    ["Two-Arm Kettlebell Clean", "Weight"],
    ["Two-Arm Kettlebell Jerk", "Weight"],
    ["Two-Arm Kettlebell Military Press", "Weight"],
    ["Two-Arm Kettlebell Row", "Weight"],
    ["Underhand Cable Pulldowns", "Weight"],
    ["Upper Back-Leg Grab", "Weight"],
    ["Upright Barbell Row", "Weight"],
    ["Upright Cable Row", "Weight"],
    ["Upright Row - With Bands", "Weight"],
    ["V-Bar Pulldown", "Weight"],
    ["V-Bar Pullup", "Weight"],
    ["Vertical Swing", "Weight"],
    ["Walking", "Weight"],
    ["Weighted Ball Hyperextension", "Weight"],
    ["Weighted Ball Side Bend", "Weight"],
    ["Weighted Bench Dip", "Weight"],
    ["Weighted Crunches", "Weight"],
    ["Weighted Jump Squat", "Weight"],
    ["Weighted Pull Ups", "Weight"],
    ["Weighted Sissy Squat", "Weight"],
    ["Weighted Sit-Ups - With Bands", "Weight"],
    ["Weighted Squat", "Weight"],
    ["Wide Stance Barbell Squat", "Weight"],
    ["Wide Stance Stiff Legs", "Weight"],
    ["Wide-Grip Barbell Bench Press", "Weight"],
    ["Wide-Grip Decline Barbell Bench Press", "Weight"],
    ["Wide-Grip Decline Barbell Pullover", "Weight"],
    ["Wide-Grip Lat Pulldown", "Weight"],
    ["Wide-Grip Pulldown Behind The Neck", "Weight"],
    ["Wide-Grip Rear Pull-Up", "Weight"],
    ["Wide-Grip Standing Barbell Curl", "Weight"],
    ["Wind Sprints", "Weight"],
    ["Windmills", "Weight"],
    ["Wrist Circles", "Weight"],
    ["Wrist Roller", "Weight"],
    ["Wrist Rotations With Straight Bar", "Weight"],
    ["Yoke Walk", "Weight"],
    ["Zercher Squats", "Weight"],
    ["Zottman Curl", "Weight"],
    ["Zottman Preacher Curl", "Weight"],
];

export default masterExerciseList;